stages:
  - test
  - build

test project:
  stage: test
  image: node:18
  script:
      - npm install
      - npm test

build project:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
